- name: Add Longhorn repository
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io

- name: Install Longhorn helm chart
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    chart_version: "{{ longhorn_version }}"
    release_namespace: longhorn-system
    create_namespace: true
    wait: true
    state: present
    values:
      defaultSettings:
        defaultDataPath: "{{ mount_point }}"
      enablePSP: false
