- name: Install open-iscsi Longhorn prerequisite
  ansible.builtin.apt:
    name: open-iscsi
    state: present

- name: Ensure the iscsid (open-iscsi) service is running
  ansible.builtin.service:
    name: iscsid
    state: started
    enabled: true

- name: Create mount point directory
  ansible.builtin.file:
    path: "{{ mount_point }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true
