- name: Expose a service using the Gateway API HTTP route spec
  kubernetes.core.k8s:
    definition:
      apiVersion: gateway.networking.k8s.io/v1beta1
      kind: HTTPRoute
      metadata:
        name: "{{ route_name }}"
        namespace: "{{ route_namespace }}"
      spec:
        hostnames:
          - "{{ route_hostname }}"
        parentRefs:
          - name: "cilium-gateway-{{ route_name }}"
            namespace: "{{ route_gateway_reference_namespace }}"
        rules:
          - backendRefs:
              - name: "{{ route_backend_service_name }}"
                port: "{{ route_backend_service_port }}"


