- name: Modify gatewateway object to add new route
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: gateway.networking.k8s.io/v1beta1
      kind: Gateway
      metadata:
        name: "cilium-gateway"
        namespace: kube-system
      spec:
        listeners:
          - protocol: HTTPS
            port: 443
            name: https-gateway
            hostname: "{{ route_hostname }}"
            tls:
              mode: Terminate
              certificateRefs:
                - name: "tls-{{ route_name }}"


- name: Expose a service using the Gateway API HTTP route spec
  kubernetes.core.k8s:
    definition:
      apiVersion: gateway.networking.k8s.io/v1beta1
      kind: HTTPRoute
      metadata:
        name: "{{ route_name }}"
        namespace: "{{ route_namespace }}"
      spec:
        hostnames:
          - "{{ route_hostname }}"
        parentRefs:
          - name: "cilium-gateway"
            namespace: "{{ route_gateway_reference_namespace }}"
        rules:
          - backendRefs:
              - name: "{{ route_backend_service_name }}"
                port: "{{ route_backend_service_port }}"
