- name: Install Helm
  ansible.builtin.shell: |
    set -o pipefail;
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    executable: /bin/bash
  when: "'server_nodes' in group_names"
  changed_when: "'server_nodes' in group_names"

- name: Move kubeconfig
  ansible.builtin.shell: |
    mkdir -p ~/.kube
    cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
    chmod 600 ~/.kube/config
  when: "'server_nodes' in group_names"
  changed_when: "'server_nodes' in group_names"


- name: Add a repository
  kubernetes.core.helm_repository:
    name: stable
    repo_url: https://helm.cilium.io/

- name: Install Cilium
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    chart_version: "{{ cilium_version }}"
    release_namespace: kube-system
    values:
      kubeProxyReplacement: true
      k8sServiceHost: "{{ cilium_service_host }}"
      k8sServicePort: "{{ cilium_service_port }}"
      ipam:
        operator:
          clusterPoolCIDR: "{{ cilium_cluster_pool_cidr }}"
      bgpControlPlane:
        enabled: true
