- name: Create kubernetes namespace
  ansible.builtin.command:
    cmd: kubectl create namespace {{ prometheus_operator_namespace }}
  changed_when: false

- name: Download Prometheus Operator bundle.yaml
  ansible.builtin.get_url:
    url: "https://github.com/prometheus-operator/prometheus-operator/releases/download/{{ prometheus_operator_version }}/bundle.yaml"
    dest: "/tmp/bundle.yaml"
    mode: "0644"
  register: download_result
  changed_when: download_result.changed

- name: Apply Prometheus Operator bundle.yaml
  ansible.builtin.command:
    cmd: kubectl apply -f /tmp/bundle.yaml -n {{ prometheus_operator_namespace }}
    creates: /tmp/bundle.yaml
  changed_when: download_result.changed


- name: Wait for Prometheus Operator to be ready
  ansible.builtin.command:
    cmd: kubectl wait --for=condition=Ready pods -l app.kubernetes.io/name=prometheus-operator -n {{ prometheus_operator_namespace }}
  changed_when: download_result.changed
