- name: Create data partition and mounts on disk
  hosts: server_nodes
  become: true
  roles:
    - create-partition


- name: Install K3s on nodes
  hosts: server_nodes
  become: true
  roles:
    - install-k3s
