- name: Create data partition and mounts on disk
  hosts: all
  become: true
  roles:
    - create-partition

- name: Install K3s on nodes
  hosts: all
  become: true
  roles:
    - install-k3s

- name: Get kubeconfig from server
  hosts: localhost
  roles:
    - get-kubeconfig

- name: Install Cilium on cluster
  hosts: localhost
  roles:
    - install-cilium

- name: Install Cert-Manager
  hosts: localhost
  roles:
    - install-cert-manager
