- name: Create data partition and mounts on disk
  hosts: all
  become: true
  roles:
    - create-partition

#
# - name: Install K3s on nodes
#  hosts: all
#  become: true
#  roles:
#    - install-k3s
